version: '3.9'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  rabbitmq:
    image: rabbitmq:4.0.3-management
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  dbdata6: