FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /worker
COPY ./app ./app
COPY ./lib ./lib

WORKDIR /worker/app
RUN dotnet publish -c Release -o /publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /publish .

ENTRYPOINT ["dotnet", "app.dll"]