name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - worker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file .\worker\dockerfile --tag womm-worker:$(date +%s)
