name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - worker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd worker &&  
            docker build --tag mwerfring/womm-worker:latest .
    - name: push
      run: |
        docker login -u mwerfring -p ${{ secrets.DOCKER_HUB_TOKEN }} 
        docker push mwerfring/womm-worker:latest